spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    httpclient:
      connect-timeout : 1000
      response-timeout : 2s

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
#make discovery locator true if you don't n need default routing configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "api-gateway"
    description: "inventory management SYSTEM GATEWAY"
    version: "1.0.0"
#
#logging:
#  level:
#    com:
#      masum:
#        gatewayserver: DEBUG



#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        sliding-window-size: 10 # at least monitor 10 request
#        permitted-number-of-calls-in-half-open-state: 2 #
#        failure-rate-threshold: 50 # if at least 50% requet failed then move to openstate from closestatre
#        wait-duration-in-open-state: 10000 # wait 10 seconds whenver try to move in half open state
#
#


#spring.application.name=api-gateway
#server.port = 8765
#
#spring.cloud.gateway.discovery.locator.enabled=true


#spring.cloud.gateway.discovery.locator.lower-case-service-id=true